(****************************************************************************)
(*                                                                          *)
(*     Projet pour Mr A. Colmerauer dans le cadre du cours de PROLOG II     *)
(*                                                                          *)
(*    (D.E.A. "Informatique et Mathématiques", Option IA, Année 87/88)      *)
(*                                                                          *)
(****************************************************************************)
(*                                                                          *)
(*  Auteur   : Christophe BISIERE                                           *)
(*                                                                          *)
(*  Date     : Le 07/01/88                                                  *)
(*                                                                          *)
(*  Language : Turbo Pascal                                                 *)
(*                                                                          *)
(*  Objet    : Interpréteur PROLOG II (syntaxe simplifiée)                  *)
(*                                                                          *)
(*                                                                          *)
(****************************************************************************)

